version: "3.8"
services:
  app:
    build:
      context: ./app
    container_name: app-container
    ports:
      - "3000:3000"
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
    container_name: proxy-container
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
